### ISSUE TITLE
The GPU memory usage is very high when the model output length is set to 500.

### ISSUE THREAD

**Issue by Minami-su** [chu-tianxiang/QuIP#2]
Typically, loading a 1.8 billion 2-bit model requires no more than 2GB of GPU memory. However, when the model output length=500, the GPU memory increases disproportionately. Is this behavior considered normal?
quantize code:
```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from quantizer import QuipQuantizer

model_name = "Qwen-1_8B-Chat"
quant_dir = "Qwen-1_8B-Chat_2bit_quip"
tokenizer = AutoTokenizer.from_pretrained(model_name,trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16,trust_remote_code=True)

quant = QuipQuantizer(codebook="E8P12", dataset="c4", nsamples=128, cache_on_gpu=True)
quant_model = quant.quantize_model(model, tokenizer)
quant.save(quant_model, quant_dir)
tokenizer.save_pretrained(quant_dir)
```
inference code:
```
from transformers import AutoTokenizer
from quantizer import load_quantized_model

quant_dir = "Qwen-1_8B-Chat_2bit2"

quant_model = load_quantized_model(quant_dir).cuda()
tokenizer = AutoTokenizer.from_pretrained(quant_dir)

input_ids = tokenizer.encode("The capital of France is", return_tensors="pt").cuda()
print(tokenizer.decode(quant_model.generate(input_ids,max_length=500, do_sample=True)[0]))
```

![image](https://github.com/chu-tianxiang/QuIP-for-all/assets/76865636/d777f33e-4cf9-4c79-86a4-6da691f9ef4d)

**Comment by chu-tianxiang** [comment]
That's weird, I was able to run LLaMA-7B with ~3gb memory. I'll check if I can reproduce this. Could you please use torch memory tools like `torch.cuda.max_memory_allocated()` to see how much are really occupied?

**Comment by Minami-su** [comment]
> That's weird, I was able to run LLaMA-7B with ~3gb memory. I'll check if I can reproduce this. Could you please use torch memory tools like `torch.cuda.max_memory_allocated()` to see how much are really occupied?

torch.cuda.max_memory_allocated() output 1876800512

**Comment by Minami-su** [comment]
![image](https://github.com/chu-tianxiang/QuIP-for-all/assets/76865636/24f79828-9b06-433d-872e-689857aa7134)

**Comment by Minami-su** [comment]
> That's weird, I was able to run LLaMA-7B with ~3gb memory. I'll check if I can reproduce this. Could you please use torch memory tools like `torch.cuda.max_memory_allocated()` to see how much are really occupied?

I downloaded your 'keyfan/Qwen-72B-Chat-2bit' model and tested the inference, and it worked fine. Perhaps there is an issue with my quantization.

**Comment by Minami-su** [comment]
> That's weird, I was able to run LLaMA-7B with ~3gb memory. I'll check if I can reproduce this. Could you please use torch memory tools like `torch.cuda.max_memory_allocated()` to see how much are really occupied?

I resolved this issue because I had previously modified 'modeling_qwen.py,' which led to the occurrence of exceptions. After deleting it and redownloading, everything returned to normal.
