### ISSUE TITLE
quip # updated

### ISSUE THREAD

**Issue by Minami-su** [chu-tianxiang/QuIP#5]
![Screenshot_2024-02-13-20-51-56-127_com twitter android](https://github.com/chu-tianxiang/QuIP-for-all/assets/76865636/8b5ebf4b-c0c1-4ae4-9c8d-3d128df3d93c)

**Comment by Minami-su** [comment]
![20240213_205435](https://github.com/chu-tianxiang/QuIP-for-all/assets/76865636/192ca7ba-9add-4c28-ba89-f6b1951619ac)

**Comment by chu-tianxiang** [comment]
Thanks for bring it up, I'll look into how to integrate the finetune-based method after the holiday.
